apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: carts-dynamodb-secret
  namespace: retail
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: carts-dynamodb-credentials
    creationPolicy: Owner
  data:
    - secretKey: tableName
      remoteRef:
        key: carts-dynamodb-secret
        property: tableName
