env:
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: orders-db-credentials
        key: host
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: orders-db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: orders-db-credentials
        key: password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: orders-db-credentials
        key: dbname

#another
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: public.ecr.aws/aws-containers/retail-store-sample-orders:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: orders-db-credentials
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-db-credentials
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orders-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: orders-db-credentials
                  key: password
